# Generated by Django 4.0.2 on 2022-03-02 19:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutcomp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Корхонамиз хакида')),
                ('title_ru', models.CharField(max_length=30, null=True, verbose_name='Корхонамиз хакида')),
                ('title_uz', models.CharField(max_length=30, null=True, verbose_name='Корхонамиз хакида')),
                ('title_en', models.CharField(max_length=30, null=True, verbose_name='Корхонамиз хакида')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('text_ru', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('text_uz', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('text_en', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='post_images', verbose_name='Фото о нашей компании')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Коментарие',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='имя пользователя')),
                ('title_ru', models.CharField(max_length=30, null=True, verbose_name='имя пользователя')),
                ('title_uz', models.CharField(max_length=30, null=True, verbose_name='имя пользователя')),
                ('title_en', models.CharField(max_length=30, null=True, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('text_ru', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('text_uz', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('text_en', models.CharField(max_length=300, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название новостей')),
                ('title_ru', models.CharField(max_length=30, null=True, verbose_name='Название новостей')),
                ('title_uz', models.CharField(max_length=30, null=True, verbose_name='Название новостей')),
                ('title_en', models.CharField(max_length=30, null=True, verbose_name='Название новостей')),
                ('text', models.CharField(max_length=300, verbose_name='Текст')),
                ('text_ru', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('text_uz', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('text_en', models.CharField(max_length=300, null=True, verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='post_images', verbose_name='Фото новостей')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название статьи')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Название статьи')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название статьи')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(max_length=1000, verbose_name='текст')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(max_length=1000, null=True, verbose_name='текст')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(max_length=1000, null=True, verbose_name='текст')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(max_length=1000, null=True, verbose_name='текст')),
                ('photo', models.ImageField(upload_to='post_images', verbose_name='выбрать фото')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Имя фамилие работающих людей')),
                ('title_ru', models.CharField(max_length=30, null=True, verbose_name='Имя фамилие работающих людей')),
                ('title_uz', models.CharField(max_length=30, null=True, verbose_name='Имя фамилие работающих людей')),
                ('title_en', models.CharField(max_length=30, null=True, verbose_name='Имя фамилие работающих людей')),
                ('totle', models.CharField(max_length=50, verbose_name='должность')),
                ('totle_ru', models.CharField(max_length=50, null=True, verbose_name='должность')),
                ('totle_uz', models.CharField(max_length=50, null=True, verbose_name='должность')),
                ('totle_en', models.CharField(max_length=50, null=True, verbose_name='должность')),
                ('tel_number', models.IntegerField(verbose_name='Номера сотрудников')),
                ('photo', models.ImageField(upload_to='post_images', verbose_name='Фоторафия сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
